name: 'Amazon Insepctor Check'
description: 'Check results of amazon inspect on image'
inputs:
  repository:
    description: 'Repository name'
    required: true
  tag:
    description: 'Tag of scanned image'
    required: true
  fail-severity: 
    description: 'The unacceptable severity of any scanned vulnerabilities'
    default: 'CRITICAL'
  initial-delay:
    description: 'Time in ms before first attempting to retrieve scan findings'
    default: '0'
  retry-delay:
    description: 'Time in ms between subsequent attempts to retrieve scan findings'
    default: '500'
  max-retries:
    description: 'Max total retries to succesfully retrieve scan findings'
    default: '10'
  validation-delay:
    description: 'Time in ms between subsequent attempts to retrieve scan findings'
    default: '5000'

outputs:
  findingSeverityCounts:
    description: 'Counts of scanned vulnerabilities grouped by severity'
runs:
  using: 'node16'
  main: 'dist/index.js'
