name: 'Amazon Insepctor Check'
description: 'Check results of amazon inspect on image'
inputs:
  repository:
    description: 'Repository name'
    required: true
  tag:
    description: 'Tag of scanned image'
    required: true
  delay:
    description: 'Time in ms between attempt to retrieve scan findings'
    default: '100'
  max_retries:
    description: 'Max total retries to succesfully retrieve scan findings'
    default: '300'
  failSeverity: 
    description: 'The unacceptable severity of any scanned vulnerabilities'
    default: 'CRITICAL'
    
outputs:
  findingSeverityCounts:
    description: 'Counts of scanned vulnerabilities grouped by severity'
runs:
  using: 'node16'
  main: 'dist/index.js'
