name: 'AWS Insepctor Check'
description: 'Check results of amazon inspect on image'

inputs:
  repository:
    description: 'Repository name'
    required: true
  tag:
    description: 'Tag of scanned image'
    required: true
  fail-on: 
    description: 'The unacceptable severity of any scanned vulnerabilities'
  ignore: 
    description: 'The vulnerabilities to ignore'
  max-retries:
    description: 'Max total retries to succesfully retrieve scan findings'
    required: true
  delay:
    description: 'Time in ms between subsequent attempts to retrieve scan findings'
    required: true
  consistency-delay:
    description: 'Time in ms between subsequent attempts to retrieve consistent scan findings'
    required: true

outputs:
  findingSeverityCounts:
    description: 'Counts of scanned vulnerabilities grouped by severity'
runs:
  using: 'node16'
  main: 'dist/index.js'
