name: test 'n build

on:
  pull_request:
    branches:
      - main
    types: 
      - opened
      - synchronize

jobs:
  test_n_build:
    name: test 'n build
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      
      - name: run tests
        run: npm run test
        
      - name: bundle
        run: npm run bundle
        
      - name: commit bundled files and test badge
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit --allow-empty -m "test badge and bundle"
          git push